/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedJoueursRouteImport } from './routes/_authenticated/joueurs'
import { Route as AuthenticatedMatchsRouteImport } from './routes/_authenticated/matchs'
import { Route as AuthenticatedMatchsIdRouteImport } from './routes/_authenticated/matchs_.$id'
import { Route as AuthenticatedMatchsNouveauRouteImport } from './routes/_authenticated/matchs_.nouveau'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJoueursRoute = AuthenticatedJoueursRouteImport.update({
  id: '/joueurs',
  path: '/joueurs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchsRoute = AuthenticatedMatchsRouteImport.update({
  id: '/matchs',
  path: '/matchs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchsIdRoute = AuthenticatedMatchsIdRouteImport.update({
  id: '/matchs_/$id',
  path: '/matchs/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchsNouveauRoute =
  AuthenticatedMatchsNouveauRouteImport.update({
    id: '/matchs_/nouveau',
    path: '/matchs/nouveau',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/joueurs': typeof AuthenticatedJoueursRoute
  '/matchs': typeof AuthenticatedMatchsRoute
  '/matchs/$id': typeof AuthenticatedMatchsIdRoute
  '/matchs/nouveau': typeof AuthenticatedMatchsNouveauRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/joueurs': typeof AuthenticatedJoueursRoute
  '/matchs': typeof AuthenticatedMatchsRoute
  '/matchs/$id': typeof AuthenticatedMatchsIdRoute
  '/matchs/nouveau': typeof AuthenticatedMatchsNouveauRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/joueurs': typeof AuthenticatedJoueursRoute
  '/_authenticated/matchs': typeof AuthenticatedMatchsRoute
  '/_authenticated/matchs_/$id': typeof AuthenticatedMatchsIdRoute
  '/_authenticated/matchs_/nouveau': typeof AuthenticatedMatchsNouveauRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/admin' | '/joueurs' | '/matchs' | '/matchs/$id' | '/matchs/nouveau'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/admin' | '/joueurs' | '/matchs' | '/matchs/$id' | '/matchs/nouveau'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/joueurs'
    | '/_authenticated/matchs'
    | '/_authenticated/matchs_/$id'
    | '/_authenticated/matchs_/nouveau'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/joueurs': {
      id: '/_authenticated/joueurs'
      path: '/joueurs'
      fullPath: '/joueurs'
      preLoaderRoute: typeof AuthenticatedJoueursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matchs': {
      id: '/_authenticated/matchs'
      path: '/matchs'
      fullPath: '/matchs'
      preLoaderRoute: typeof AuthenticatedMatchsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matchs_/$id': {
      id: '/_authenticated/matchs_/$id'
      path: '/matchs/$id'
      fullPath: '/matchs/$id'
      preLoaderRoute: typeof AuthenticatedMatchsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matchs_/nouveau': {
      id: '/_authenticated/matchs_/nouveau'
      path: '/matchs/nouveau'
      fullPath: '/matchs/nouveau'
      preLoaderRoute: typeof AuthenticatedMatchsNouveauRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedJoueursRoute: typeof AuthenticatedJoueursRoute
  AuthenticatedMatchsRoute: typeof AuthenticatedMatchsRoute
  AuthenticatedMatchsIdRoute: typeof AuthenticatedMatchsIdRoute
  AuthenticatedMatchsNouveauRoute: typeof AuthenticatedMatchsNouveauRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedJoueursRoute: AuthenticatedJoueursRoute,
  AuthenticatedMatchsRoute: AuthenticatedMatchsRoute,
  AuthenticatedMatchsIdRoute: AuthenticatedMatchsIdRoute,
  AuthenticatedMatchsNouveauRoute: AuthenticatedMatchsNouveauRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
